
service: pruebacontinuapython

frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: us-east-1
  lambdaHashingVersion: 20201221



functions:
  hello:
    handler: handler.hello
